use super::{
    AbilityDef, AbilityTarget, DamageType, EncounterDef, EnemyDef, EnemyRole, ResourceKind,
    StatusKind,
};
use crate::character::MajorSkill;
use crate::inventory::{ItemRarity, LootTableEntry, WeaponKind};

const WOLF_LOOT: &[LootTableEntry] = &[LootTableEntry {
    item_type: "wolf_pelt",
    min_qty: 1,
    max_qty: 2,
    weight: 2,
    min_rarity: ItemRarity::Common,
}];

const BANDIT_LOOT: &[LootTableEntry] = &[
    LootTableEntry {
        item_type: "bandit_seal",
        min_qty: 1,
        max_qty: 1,
        weight: 2,
        min_rarity: ItemRarity::Common,
    },
    LootTableEntry {
        item_type: "old_map",
        min_qty: 1,
        max_qty: 1,
        weight: 4,
        min_rarity: ItemRarity::Uncommon,
    },
];

const UNDEAD_LOOT: &[LootTableEntry] = &[LootTableEntry {
    item_type: "grave_ash",
    min_qty: 1,
    max_qty: 2,
    weight: 2,
    min_rarity: ItemRarity::Rare,
}];

const MOOR_UNDEAD_LOOT: &[LootTableEntry] = &[
    LootTableEntry {
        item_type: "grave_ash",
        min_qty: 1,
        max_qty: 2,
        weight: 2,
        min_rarity: ItemRarity::Rare,
    },
    LootTableEntry {
        item_type: "cipher_scroll",
        min_qty: 1,
        max_qty: 1,
        weight: 4,
        min_rarity: ItemRarity::Rare,
    },
];

pub const ABILITIES: &[AbilityDef] = &[
    AbilityDef {
        id: "guard_stance",
        name: "Guard Stance",
        description: "Raise guard and harden against the next assault.",
        resource_kind: Some(ResourceKind::Stamina),
        cost: 6,
        cooldown: 2,
        target: AbilityTarget::SelfTarget,
        accuracy_bonus: 0,
        damage_min: 0,
        damage_max: 0,
        damage_type: DamageType::Physical,
        scaling_stat: MajorSkill::Constitution,
        apply_status: None,
        self_status: Some((StatusKind::Guard, 2, 4)),
        heal_amount: 0,
    },
    AbilityDef {
        id: "cleaving_blow",
        name: "Cleaving Blow",
        description: "A punishing martial strike that can leave the foe weakened.",
        resource_kind: Some(ResourceKind::Stamina),
        cost: 8,
        cooldown: 2,
        target: AbilityTarget::Enemy,
        accuracy_bonus: 2,
        damage_min: 8,
        damage_max: 13,
        damage_type: DamageType::Physical,
        scaling_stat: MajorSkill::Strength,
        apply_status: Some((StatusKind::Weakness, 2, 2)),
        self_status: None,
        heal_amount: 0,
    },
    AbilityDef {
        id: "shield_bash",
        name: "Shield Bash",
        description: "Crash into the enemy and force a short stun.",
        resource_kind: Some(ResourceKind::Stamina),
        cost: 10,
        cooldown: 3,
        target: AbilityTarget::Enemy,
        accuracy_bonus: 1,
        damage_min: 6,
        damage_max: 10,
        damage_type: DamageType::Physical,
        scaling_stat: MajorSkill::Strength,
        apply_status: Some((StatusKind::Stun, 1, 1)),
        self_status: None,
        heal_amount: 0,
    },
    AbilityDef {
        id: "hunters_mark",
        name: "Hunter's Mark",
        description: "Mark a target to open them to follow-up damage.",
        resource_kind: Some(ResourceKind::Stamina),
        cost: 7,
        cooldown: 2,
        target: AbilityTarget::Enemy,
        accuracy_bonus: 3,
        damage_min: 5,
        damage_max: 8,
        damage_type: DamageType::Physical,
        scaling_stat: MajorSkill::Dexterity,
        apply_status: Some((StatusKind::Weakness, 2, 2)),
        self_status: None,
        heal_amount: 0,
    },
    AbilityDef {
        id: "volley",
        name: "Volley",
        description: "Loose a punishing shot with high opening pressure.",
        resource_kind: Some(ResourceKind::Stamina),
        cost: 9,
        cooldown: 2,
        target: AbilityTarget::Enemy,
        accuracy_bonus: 2,
        damage_min: 8,
        damage_max: 12,
        damage_type: DamageType::Physical,
        scaling_stat: MajorSkill::Dexterity,
        apply_status: None,
        self_status: None,
        heal_amount: 0,
    },
    AbilityDef {
        id: "crippling_shot",
        name: "Crippling Shot",
        description: "A precision strike that slows the enemy's response.",
        resource_kind: Some(ResourceKind::Stamina),
        cost: 10,
        cooldown: 3,
        target: AbilityTarget::Enemy,
        accuracy_bonus: 2,
        damage_min: 7,
        damage_max: 10,
        damage_type: DamageType::Physical,
        scaling_stat: MajorSkill::Dexterity,
        apply_status: Some((StatusKind::Weakness, 3, 2)),
        self_status: None,
        heal_amount: 0,
    },
    AbilityDef {
        id: "ember_burst",
        name: "Ember Burst",
        description: "A burst of heat that leaves the target burning.",
        resource_kind: Some(ResourceKind::Mana),
        cost: 8,
        cooldown: 1,
        target: AbilityTarget::Enemy,
        accuracy_bonus: 2,
        damage_min: 7,
        damage_max: 11,
        damage_type: DamageType::Fire,
        scaling_stat: MajorSkill::Intelligence,
        apply_status: Some((StatusKind::Burn, 2, 3)),
        self_status: None,
        heal_amount: 0,
    },
    AbilityDef {
        id: "frost_lance",
        name: "Frost Lance",
        description: "A cold spear of force that cuts and slows.",
        resource_kind: Some(ResourceKind::Mana),
        cost: 9,
        cooldown: 2,
        target: AbilityTarget::Enemy,
        accuracy_bonus: 2,
        damage_min: 8,
        damage_max: 12,
        damage_type: DamageType::Frost,
        scaling_stat: MajorSkill::Intelligence,
        apply_status: Some((StatusKind::Weakness, 2, 1)),
        self_status: None,
        heal_amount: 0,
    },
    AbilityDef {
        id: "storm_surge",
        name: "Storm Surge",
        description: "A violent discharge that overwhelms the target's defenses.",
        resource_kind: Some(ResourceKind::Mana),
        cost: 12,
        cooldown: 3,
        target: AbilityTarget::Enemy,
        accuracy_bonus: 3,
        damage_min: 10,
        damage_max: 14,
        damage_type: DamageType::Lightning,
        scaling_stat: MajorSkill::Intelligence,
        apply_status: None,
        self_status: None,
        heal_amount: 0,
    },
    AbilityDef {
        id: "dirty_cut",
        name: "Dirty Cut",
        description: "A jagged slice meant to keep the wound open.",
        resource_kind: Some(ResourceKind::Stamina),
        cost: 7,
        cooldown: 1,
        target: AbilityTarget::Enemy,
        accuracy_bonus: 3,
        damage_min: 5,
        damage_max: 9,
        damage_type: DamageType::Physical,
        scaling_stat: MajorSkill::Dexterity,
        apply_status: Some((StatusKind::Bleed, 2, 3)),
        self_status: None,
        heal_amount: 0,
    },
    AbilityDef {
        id: "evasion",
        name: "Evasion",
        description: "Slip into a guarded stance and recover breath.",
        resource_kind: Some(ResourceKind::Stamina),
        cost: 6,
        cooldown: 2,
        target: AbilityTarget::SelfTarget,
        accuracy_bonus: 0,
        damage_min: 0,
        damage_max: 0,
        damage_type: DamageType::Physical,
        scaling_stat: MajorSkill::Dexterity,
        apply_status: None,
        self_status: Some((StatusKind::Guard, 1, 5)),
        heal_amount: 0,
    },
    AbilityDef {
        id: "shadow_flurry",
        name: "Shadow Flurry",
        description: "A flurry of cuts delivered from broken tempo.",
        resource_kind: Some(ResourceKind::Stamina),
        cost: 11,
        cooldown: 3,
        target: AbilityTarget::Enemy,
        accuracy_bonus: 3,
        damage_min: 9,
        damage_max: 13,
        damage_type: DamageType::Shadow,
        scaling_stat: MajorSkill::Dexterity,
        apply_status: Some((StatusKind::Bleed, 3, 2)),
        self_status: None,
        heal_amount: 0,
    },
    AbilityDef {
        id: "radiant_slam",
        name: "Radiant Slam",
        description: "Drive holy force through steel and shield.",
        resource_kind: Some(ResourceKind::Stamina),
        cost: 8,
        cooldown: 2,
        target: AbilityTarget::Enemy,
        accuracy_bonus: 2,
        damage_min: 7,
        damage_max: 11,
        damage_type: DamageType::Holy,
        scaling_stat: MajorSkill::Strength,
        apply_status: None,
        self_status: Some((StatusKind::Guard, 1, 2)),
        heal_amount: 0,
    },
    AbilityDef {
        id: "vow_guard",
        name: "Vow Guard",
        description: "Swear the line will hold and reinforce your defense.",
        resource_kind: Some(ResourceKind::Mana),
        cost: 6,
        cooldown: 2,
        target: AbilityTarget::SelfTarget,
        accuracy_bonus: 0,
        damage_min: 0,
        damage_max: 0,
        damage_type: DamageType::Holy,
        scaling_stat: MajorSkill::Charisma,
        apply_status: None,
        self_status: Some((StatusKind::Guard, 2, 5)),
        heal_amount: 0,
    },
    AbilityDef {
        id: "lay_on_hands",
        name: "Lay on Hands",
        description: "Restore wounds with a surge of divine conviction.",
        resource_kind: Some(ResourceKind::Mana),
        cost: 10,
        cooldown: 3,
        target: AbilityTarget::SelfTarget,
        accuracy_bonus: 0,
        damage_min: 0,
        damage_max: 0,
        damage_type: DamageType::Holy,
        scaling_stat: MajorSkill::Charisma,
        apply_status: None,
        self_status: Some((StatusKind::Regen, 2, 4)),
        heal_amount: 18,
    },
    AbilityDef {
        id: "healing_prayer",
        name: "Healing Prayer",
        description: "A brief prayer that restores life and steadies the soul.",
        resource_kind: Some(ResourceKind::Mana),
        cost: 8,
        cooldown: 2,
        target: AbilityTarget::SelfTarget,
        accuracy_bonus: 0,
        damage_min: 0,
        damage_max: 0,
        damage_type: DamageType::Holy,
        scaling_stat: MajorSkill::Wisdom,
        apply_status: None,
        self_status: Some((StatusKind::Regen, 2, 5)),
        heal_amount: 16,
    },
    AbilityDef {
        id: "smite_undead",
        name: "Smite Undead",
        description: "Condemn unquiet dead with radiant force.",
        resource_kind: Some(ResourceKind::Mana),
        cost: 9,
        cooldown: 2,
        target: AbilityTarget::Enemy,
        accuracy_bonus: 3,
        damage_min: 8,
        damage_max: 12,
        damage_type: DamageType::Holy,
        scaling_stat: MajorSkill::Wisdom,
        apply_status: None,
        self_status: None,
        heal_amount: 0,
    },
    AbilityDef {
        id: "purge",
        name: "Purge",
        description: "Scour toxins and foul magic from the field.",
        resource_kind: Some(ResourceKind::Mana),
        cost: 10,
        cooldown: 3,
        target: AbilityTarget::Enemy,
        accuracy_bonus: 2,
        damage_min: 6,
        damage_max: 10,
        damage_type: DamageType::Holy,
        scaling_stat: MajorSkill::Wisdom,
        apply_status: Some((StatusKind::Weakness, 2, 2)),
        self_status: Some((StatusKind::Regen, 1, 4)),
        heal_amount: 0,
    },
    AbilityDef {
        id: "rabid_bite",
        name: "Rabid Bite",
        description: "A savage bite that leaves venom in the wound.",
        resource_kind: None,
        cost: 0,
        cooldown: 3,
        target: AbilityTarget::Enemy,
        accuracy_bonus: 1,
        damage_min: 4,
        damage_max: 6,
        damage_type: DamageType::Poison,
        scaling_stat: MajorSkill::Strength,
        apply_status: Some((StatusKind::Poison, 2, 2)),
        self_status: None,
        heal_amount: 0,
    },
    AbilityDef {
        id: "raider_gash",
        name: "Raider Gash",
        description: "A brutal slash meant to leave the target bleeding.",
        resource_kind: None,
        cost: 0,
        cooldown: 3,
        target: AbilityTarget::Enemy,
        accuracy_bonus: 1,
        damage_min: 5,
        damage_max: 8,
        damage_type: DamageType::Physical,
        scaling_stat: MajorSkill::Strength,
        apply_status: Some((StatusKind::Bleed, 2, 2)),
        self_status: None,
        heal_amount: 0,
    },
    AbilityDef {
        id: "grave_bolt",
        name: "Grave Bolt",
        description: "A cold shard of necrotic force from the barrow dead.",
        resource_kind: Some(ResourceKind::Mana),
        cost: 5,
        cooldown: 2,
        target: AbilityTarget::Enemy,
        accuracy_bonus: 1,
        damage_min: 5,
        damage_max: 8,
        damage_type: DamageType::Shadow,
        scaling_stat: MajorSkill::Intelligence,
        apply_status: Some((StatusKind::Weakness, 2, 1)),
        self_status: None,
        heal_amount: 0,
    },
];

pub const ENEMIES: &[EnemyDef] = &[
    EnemyDef {
        id: "wild_wolf",
        name: "Wild Wolf",
        family: "Beast",
        role: EnemyRole::Skirmisher,
        level: 1,
        hp: 24,
        mana: 0,
        stamina: 10,
        attack_bonus: 3,
        defense: 10,
        initiative: 3,
        damage_min: 3,
        damage_max: 5,
        weapon_kind: WeaponKind::Melee,
        ability_ids: &["rabid_bite"],
        loot: WOLF_LOOT,
        reward_xp: 20,
        reward_gold: 8,
    },
    EnemyDef {
        id: "alpha_wolf",
        name: "Alpha Wolf",
        family: "Beast",
        role: EnemyRole::Brute,
        level: 2,
        hp: 32,
        mana: 0,
        stamina: 12,
        attack_bonus: 4,
        defense: 11,
        initiative: 2,
        damage_min: 4,
        damage_max: 7,
        weapon_kind: WeaponKind::Melee,
        ability_ids: &["rabid_bite"],
        loot: WOLF_LOOT,
        reward_xp: 28,
        reward_gold: 12,
    },
    EnemyDef {
        id: "road_raider",
        name: "Road Raider",
        family: "Bandit",
        role: EnemyRole::Brute,
        level: 2,
        hp: 32,
        mana: 0,
        stamina: 14,
        attack_bonus: 4,
        defense: 11,
        initiative: 2,
        damage_min: 4,
        damage_max: 7,
        weapon_kind: WeaponKind::Melee,
        ability_ids: &["raider_gash"],
        loot: BANDIT_LOOT,
        reward_xp: 28,
        reward_gold: 15,
    },
    EnemyDef {
        id: "bandit_bowman",
        name: "Bandit Bowman",
        family: "Bandit",
        role: EnemyRole::Skirmisher,
        level: 2,
        hp: 26,
        mana: 0,
        stamina: 12,
        attack_bonus: 4,
        defense: 10,
        initiative: 4,
        damage_min: 3,
        damage_max: 6,
        weapon_kind: WeaponKind::Ranged,
        ability_ids: &[],
        loot: BANDIT_LOOT,
        reward_xp: 24,
        reward_gold: 12,
    },
    EnemyDef {
        id: "gravebound",
        name: "Gravebound",
        family: "Undead",
        role: EnemyRole::Brute,
        level: 3,
        hp: 38,
        mana: 4,
        stamina: 12,
        attack_bonus: 5,
        defense: 12,
        initiative: 2,
        damage_min: 5,
        damage_max: 8,
        weapon_kind: WeaponKind::Melee,
        ability_ids: &["grave_bolt"],
        loot: UNDEAD_LOOT,
        reward_xp: 34,
        reward_gold: 18,
    },
    EnemyDef {
        id: "grave_channeler",
        name: "Grave Channeler",
        family: "Undead",
        role: EnemyRole::Caster,
        level: 3,
        hp: 28,
        mana: 16,
        stamina: 8,
        attack_bonus: 4,
        defense: 11,
        initiative: 3,
        damage_min: 3,
        damage_max: 6,
        weapon_kind: WeaponKind::Magic,
        ability_ids: &["grave_bolt"],
        loot: UNDEAD_LOOT,
        reward_xp: 38,
        reward_gold: 22,
    },
    EnemyDef {
        id: "moor_shambler",
        name: "Moor Shambler",
        family: "Undead",
        role: EnemyRole::Brute,
        level: 4,
        hp: 44,
        mana: 4,
        stamina: 14,
        attack_bonus: 5,
        defense: 13,
        initiative: 1,
        damage_min: 6,
        damage_max: 9,
        weapon_kind: WeaponKind::Melee,
        ability_ids: &["grave_bolt"],
        loot: MOOR_UNDEAD_LOOT,
        reward_xp: 42,
        reward_gold: 22,
    },
    EnemyDef {
        id: "moor_channeler",
        name: "Moor Channeler",
        family: "Undead",
        role: EnemyRole::Caster,
        level: 4,
        hp: 32,
        mana: 20,
        stamina: 10,
        attack_bonus: 5,
        defense: 12,
        initiative: 3,
        damage_min: 4,
        damage_max: 7,
        weapon_kind: WeaponKind::Magic,
        ability_ids: &["grave_bolt"],
        loot: MOOR_UNDEAD_LOOT,
        reward_xp: 46,
        reward_gold: 26,
    },
];

pub const ENCOUNTERS: &[EncounterDef] = &[
    EncounterDef {
        id: "beast_hunt",
        name: "Beast Hunt",
        environment_tags: &["woods", "brush"],
        enemies: &["wild_wolf"],
    },
    EncounterDef {
        id: "beast_alpha",
        name: "Alpha Pack",
        environment_tags: &["woods", "moonlit"],
        enemies: &["alpha_wolf", "wild_wolf"],
    },
    EncounterDef {
        id: "bandit_ambush",
        name: "Bandit Ambush",
        environment_tags: &["road", "ditch"],
        enemies: &["road_raider", "bandit_bowman"],
    },
    EncounterDef {
        id: "bandit_raiders",
        name: "Raider Patrol",
        environment_tags: &["road", "rain"],
        enemies: &["road_raider", "road_raider"],
    },
    EncounterDef {
        id: "undead_patrol",
        name: "Undead Patrol",
        environment_tags: &["barrow", "ash"],
        enemies: &["gravebound", "gravebound"],
    },
    EncounterDef {
        id: "barrow_rites",
        name: "Barrow Rites",
        environment_tags: &["barrow", "ritual"],
        enemies: &["grave_channeler", "gravebound"],
    },
    EncounterDef {
        id: "moor_shamble",
        name: "Moor Shamble",
        environment_tags: &["moor", "fog"],
        enemies: &["moor_shambler", "moor_shambler"],
    },
    EncounterDef {
        id: "moor_channeling",
        name: "Moor Channeling",
        environment_tags: &["moor", "ritual"],
        enemies: &["moor_channeler", "moor_shambler"],
    },
];

pub fn ability_def(id: &str) -> Option<&'static AbilityDef> {
    ABILITIES.iter().find(|ability| ability.id == id)
}

pub fn enemy_def(id: &str) -> &'static EnemyDef {
    ENEMIES
        .iter()
        .find(|enemy| enemy.id == id)
        .unwrap_or(&ENEMIES[0])
}

pub(super) fn enemy_def_by_name(name: &str) -> &'static EnemyDef {
    ENEMIES
        .iter()
        .find(|enemy| enemy.name == name)
        .unwrap_or(&ENEMIES[0])
}

pub fn encounter_def(id: &str) -> &'static EncounterDef {
    ENCOUNTERS
        .iter()
        .find(|encounter| encounter.id == id)
        .unwrap_or(&ENCOUNTERS[0])
}
