use super::{
    AttackOption, EquipSlot, EquipmentStats, ItemDef, ItemEffect, ItemKind, ItemRarity, WeaponKind,
};
use crate::character::ResistanceProfile;

const ZERO_RESISTANCES: ResistanceProfile = ResistanceProfile {
    physical: 0,
    fire: 0,
    frost: 0,
    lightning: 0,
    poison: 0,
    holy: 0,
    shadow: 0,
};

const ZERO_EQUIPMENT_STATS: EquipmentStats = EquipmentStats {
    armor: 0,
    attack_bonus: 0,
    spell_power: 0,
    crit_bonus: 0,
    initiative_bonus: 0,
    resistances: ZERO_RESISTANCES,
};

const IRON_SWORD_ATTACKS: &[AttackOption] = &[
    AttackOption {
        name: "Slash",
        accuracy_bonus: 2,
        min_damage: 5,
        max_damage: 9,
    },
    AttackOption {
        name: "Lunge",
        accuracy_bonus: 1,
        min_damage: 7,
        max_damage: 11,
    },
];

const TWIN_DAGGER_ATTACKS: &[AttackOption] = &[
    AttackOption {
        name: "Quick Slash",
        accuracy_bonus: 3,
        min_damage: 4,
        max_damage: 7,
    },
    AttackOption {
        name: "Backstab",
        accuracy_bonus: 1,
        min_damage: 6,
        max_damage: 10,
    },
];

const BOW_ATTACKS: &[AttackOption] = &[
    AttackOption {
        name: "Quick Shot",
        accuracy_bonus: 3,
        min_damage: 4,
        max_damage: 8,
    },
    AttackOption {
        name: "Power Draw",
        accuracy_bonus: 1,
        min_damage: 6,
        max_damage: 10,
    },
];

const STAFF_ATTACKS: &[AttackOption] = &[
    AttackOption {
        name: "Arcane Bolt",
        accuracy_bonus: 2,
        min_damage: 5,
        max_damage: 9,
    },
    AttackOption {
        name: "Frost Tap",
        accuracy_bonus: 2,
        min_damage: 4,
        max_damage: 8,
    },
];

const WAND_ATTACKS: &[AttackOption] = &[
    AttackOption {
        name: "Fire Spark",
        accuracy_bonus: 2,
        min_damage: 5,
        max_damage: 10,
    },
    AttackOption {
        name: "Ember Lance",
        accuracy_bonus: 1,
        min_damage: 7,
        max_damage: 11,
    },
];

const HEALTH_EFFECT: &[ItemEffect] = &[ItemEffect::HealHp(24)];
const BANDAGE_EFFECT: &[ItemEffect] = &[ItemEffect::HealHp(12)];
const RATION_EFFECT: &[ItemEffect] = &[ItemEffect::HealHp(8), ItemEffect::RestoreStamina(6)];
const MANA_EFFECT: &[ItemEffect] = &[ItemEffect::RestoreMana(18)];
const STAMINA_EFFECT: &[ItemEffect] = &[ItemEffect::RestoreStamina(18)];
const ANTIDOTE_EFFECT: &[ItemEffect] = &[ItemEffect::CurePoison];

pub const ITEM_CATALOG: &[ItemDef] = &[
    ItemDef {
        item_type: "health_potion",
        name: "Health Potion",
        description: "A bright red tonic that closes cuts and steadies breathing.",
        kind: ItemKind::Consumable,
        rarity: ItemRarity::Common,
        base_value: 18,
        stackable: true,
        effects: HEALTH_EFFECT,
        equip_slot: None,
        weapon_kind: None,
        attacks: &[],
        equipment_stats: ZERO_EQUIPMENT_STATS,
    },
    ItemDef {
        item_type: "bandage",
        name: "Bandage",
        description: "Quick field wrap for patching lighter injuries.",
        kind: ItemKind::Consumable,
        rarity: ItemRarity::Common,
        base_value: 8,
        stackable: true,
        effects: BANDAGE_EFFECT,
        equip_slot: None,
        weapon_kind: None,
        attacks: &[],
        equipment_stats: ZERO_EQUIPMENT_STATS,
    },
    ItemDef {
        item_type: "ration",
        name: "Ration",
        description: "Salt meat, hard bread, and enough calories to keep moving.",
        kind: ItemKind::Consumable,
        rarity: ItemRarity::Common,
        base_value: 6,
        stackable: true,
        effects: RATION_EFFECT,
        equip_slot: None,
        weapon_kind: None,
        attacks: &[],
        equipment_stats: ZERO_EQUIPMENT_STATS,
    },
    ItemDef {
        item_type: "mana_tonic",
        name: "Mana Tonic",
        description: "A bitter draught that restores spell reserve.",
        kind: ItemKind::Consumable,
        rarity: ItemRarity::Uncommon,
        base_value: 22,
        stackable: true,
        effects: MANA_EFFECT,
        equip_slot: None,
        weapon_kind: None,
        attacks: &[],
        equipment_stats: ZERO_EQUIPMENT_STATS,
    },
    ItemDef {
        item_type: "stamina_draught",
        name: "Stamina Draught",
        description: "Restores drive and clears the ache from tired limbs.",
        kind: ItemKind::Consumable,
        rarity: ItemRarity::Uncommon,
        base_value: 20,
        stackable: true,
        effects: STAMINA_EFFECT,
        equip_slot: None,
        weapon_kind: None,
        attacks: &[],
        equipment_stats: ZERO_EQUIPMENT_STATS,
    },
    ItemDef {
        item_type: "antidote",
        name: "Antidote",
        description: "Neutralizes common toxins and clears poison.",
        kind: ItemKind::Consumable,
        rarity: ItemRarity::Common,
        base_value: 14,
        stackable: true,
        effects: ANTIDOTE_EFFECT,
        equip_slot: None,
        weapon_kind: None,
        attacks: &[],
        equipment_stats: ZERO_EQUIPMENT_STATS,
    },
    ItemDef {
        item_type: "iron_sword",
        name: "Iron Sword",
        description: "Reliable steel favored by militia and caravan guards.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Common,
        base_value: 42,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Weapon),
        weapon_kind: Some(WeaponKind::Melee),
        attacks: IRON_SWORD_ATTACKS,
        equipment_stats: EquipmentStats {
            armor: 0,
            attack_bonus: 2,
            spell_power: 0,
            crit_bonus: 0,
            initiative_bonus: 0,
            resistances: ResistanceProfile {
                physical: 0,
                fire: 0,
                frost: 0,
                lightning: 0,
                poison: 0,
                holy: 0,
                shadow: 0,
            },
        },
    },
    ItemDef {
        item_type: "twin_daggers",
        name: "Twin Daggers",
        description: "Light blades built for precise openings and dirty work.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Uncommon,
        base_value: 55,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Weapon),
        weapon_kind: Some(WeaponKind::Melee),
        attacks: TWIN_DAGGER_ATTACKS,
        equipment_stats: EquipmentStats {
            armor: 0,
            attack_bonus: 1,
            spell_power: 0,
            crit_bonus: 3,
            initiative_bonus: 2,
            resistances: ResistanceProfile {
                physical: 0,
                fire: 0,
                frost: 0,
                lightning: 0,
                poison: 0,
                holy: 0,
                shadow: 0,
            },
        },
    },
    ItemDef {
        item_type: "hunting_bow",
        name: "Hunting Bow",
        description: "Yew bow suited to measured pressure at range.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Common,
        base_value: 48,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Weapon),
        weapon_kind: Some(WeaponKind::Ranged),
        attacks: BOW_ATTACKS,
        equipment_stats: EquipmentStats {
            armor: 0,
            attack_bonus: 2,
            spell_power: 0,
            crit_bonus: 1,
            initiative_bonus: 1,
            resistances: ZERO_RESISTANCES,
        },
    },
    ItemDef {
        item_type: "apprentice_staff",
        name: "Apprentice Staff",
        description: "A runed staff that steadies novice channeling.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Common,
        base_value: 50,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Weapon),
        weapon_kind: Some(WeaponKind::Magic),
        attacks: STAFF_ATTACKS,
        equipment_stats: EquipmentStats {
            armor: 0,
            attack_bonus: 1,
            spell_power: 3,
            crit_bonus: 0,
            initiative_bonus: 0,
            resistances: ZERO_RESISTANCES,
        },
    },
    ItemDef {
        item_type: "ember_wand",
        name: "Ember Wand",
        description: "A refined focus for aggressive elemental casting.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Rare,
        base_value: 88,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Weapon),
        weapon_kind: Some(WeaponKind::Magic),
        attacks: WAND_ATTACKS,
        equipment_stats: EquipmentStats {
            armor: 0,
            attack_bonus: 1,
            spell_power: 5,
            crit_bonus: 1,
            initiative_bonus: 1,
            resistances: ZERO_RESISTANCES,
        },
    },
    ItemDef {
        item_type: "wooden_shield",
        name: "Wooden Shield",
        description: "Simple protection that keeps the worst of a blow off your ribs.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Common,
        base_value: 28,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Shield),
        weapon_kind: None,
        attacks: &[],
        equipment_stats: EquipmentStats {
            armor: 3,
            attack_bonus: 0,
            spell_power: 0,
            crit_bonus: 0,
            initiative_bonus: 0,
            resistances: ResistanceProfile {
                physical: 1,
                ..ZERO_RESISTANCES
            },
        },
    },
    ItemDef {
        item_type: "leather_chest",
        name: "Leather Jerkin",
        description: "Sturdy boiled leather with enough give for active fighting.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Common,
        base_value: 32,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Chest),
        weapon_kind: None,
        attacks: &[],
        equipment_stats: EquipmentStats {
            armor: 4,
            attack_bonus: 0,
            spell_power: 0,
            crit_bonus: 0,
            initiative_bonus: 0,
            resistances: ResistanceProfile {
                physical: 1,
                ..ZERO_RESISTANCES
            },
        },
    },
    ItemDef {
        item_type: "leather_legs",
        name: "Leather Greaves",
        description: "Flexible leg guards for long marches and quick turns.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Common,
        base_value: 24,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Legs),
        weapon_kind: None,
        attacks: &[],
        equipment_stats: EquipmentStats {
            armor: 2,
            attack_bonus: 0,
            spell_power: 0,
            crit_bonus: 0,
            initiative_bonus: 1,
            resistances: ZERO_RESISTANCES,
        },
    },
    ItemDef {
        item_type: "traveler_cloak",
        name: "Traveler's Cloak",
        description: "Wool and weather-proofing stitched for hard roads.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Common,
        base_value: 20,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Cape),
        weapon_kind: None,
        attacks: &[],
        equipment_stats: EquipmentStats {
            armor: 1,
            attack_bonus: 0,
            spell_power: 0,
            crit_bonus: 0,
            initiative_bonus: 1,
            resistances: ResistanceProfile {
                frost: 1,
                ..ZERO_RESISTANCES
            },
        },
    },
    ItemDef {
        item_type: "silver_amulet",
        name: "Silver Amulet",
        description: "An old protective charm used to ward restless spirits.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Uncommon,
        base_value: 60,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Neck),
        weapon_kind: None,
        attacks: &[],
        equipment_stats: EquipmentStats {
            armor: 0,
            attack_bonus: 0,
            spell_power: 2,
            crit_bonus: 0,
            initiative_bonus: 0,
            resistances: ResistanceProfile {
                holy: 2,
                shadow: 1,
                ..ZERO_RESISTANCES
            },
        },
    },
    ItemDef {
        item_type: "wolf_pelt",
        name: "Wolf Pelt",
        description: "A thick hide that sells well to fur traders.",
        kind: ItemKind::Loot,
        rarity: ItemRarity::Common,
        base_value: 12,
        stackable: true,
        effects: &[],
        equip_slot: None,
        weapon_kind: None,
        attacks: &[],
        equipment_stats: ZERO_EQUIPMENT_STATS,
    },
    ItemDef {
        item_type: "bandit_seal",
        name: "Bandit Seal",
        description: "Stamped insignia stolen from raider captains.",
        kind: ItemKind::Loot,
        rarity: ItemRarity::Uncommon,
        base_value: 20,
        stackable: true,
        effects: &[],
        equip_slot: None,
        weapon_kind: None,
        attacks: &[],
        equipment_stats: ZERO_EQUIPMENT_STATS,
    },
    ItemDef {
        item_type: "grave_ash",
        name: "Grave Ash",
        description: "Powder scraped from an active barrow's inner crypt.",
        kind: ItemKind::Loot,
        rarity: ItemRarity::Rare,
        base_value: 26,
        stackable: true,
        effects: &[],
        equip_slot: None,
        weapon_kind: None,
        attacks: &[],
        equipment_stats: ZERO_EQUIPMENT_STATS,
    },
    ItemDef {
        item_type: "old_map",
        name: "Old Map",
        description: "A courier chart detailing paths across the Sunken Road.",
        kind: ItemKind::Quest,
        rarity: ItemRarity::Uncommon,
        base_value: 0,
        stackable: true,
        effects: &[],
        equip_slot: None,
        weapon_kind: None,
        attacks: &[],
        equipment_stats: ZERO_EQUIPMENT_STATS,
    },
];

pub fn find_def(item_type: &str) -> Option<&'static ItemDef> {
    ITEM_CATALOG.iter().find(|item| item.item_type == item_type)
}

pub fn gear_package_items(gear_name: &str) -> &'static [(&'static str, &'static str)] {
    match gear_name {
        "Melee Kit" => &[
            ("weapon", "iron_sword"),
            ("shield", "wooden_shield"),
            ("chest", "leather_chest"),
            ("legs", "leather_legs"),
        ],
        "Ranged Kit" => &[
            ("weapon", "hunting_bow"),
            ("cape", "traveler_cloak"),
            ("chest", "leather_chest"),
            ("legs", "leather_legs"),
        ],
        "Arcane Kit" => &[
            ("weapon", "apprentice_staff"),
            ("neck", "silver_amulet"),
            ("cape", "traveler_cloak"),
        ],
        "Stealth Kit" => &[
            ("weapon", "twin_daggers"),
            ("cape", "traveler_cloak"),
            ("chest", "leather_chest"),
            ("legs", "leather_legs"),
        ],
        _ => &[],
    }
}
