use super::{
    AttackOption, EquipSlot, EquipmentStats, ItemDef, ItemEffect, ItemKind, ItemRarity, WeaponKind,
};
use crate::character::ResistanceProfile;

const ZERO_RESISTANCES: ResistanceProfile = ResistanceProfile {
    physical: 0,
    fire: 0,
    frost: 0,
    lightning: 0,
    poison: 0,
    holy: 0,
    shadow: 0,
};

const ZERO_EQUIPMENT_STATS: EquipmentStats = EquipmentStats {
    armor: 0,
    attack_bonus: 0,
    spell_power: 0,
    crit_bonus: 0,
    initiative_bonus: 0,
    resistances: ZERO_RESISTANCES,
};

const IRON_SWORD_ATTACKS: &[AttackOption] = &[
    AttackOption {
        name: "Slash",
        accuracy_bonus: 2,
        min_damage: 5,
        max_damage: 9,
    },
    AttackOption {
        name: "Lunge",
        accuracy_bonus: 1,
        min_damage: 7,
        max_damage: 11,
    },
];

const TWIN_DAGGER_ATTACKS: &[AttackOption] = &[
    AttackOption {
        name: "Quick Slash",
        accuracy_bonus: 3,
        min_damage: 4,
        max_damage: 7,
    },
    AttackOption {
        name: "Backstab",
        accuracy_bonus: 1,
        min_damage: 6,
        max_damage: 10,
    },
];

const BOW_ATTACKS: &[AttackOption] = &[
    AttackOption {
        name: "Quick Shot",
        accuracy_bonus: 3,
        min_damage: 4,
        max_damage: 8,
    },
    AttackOption {
        name: "Power Draw",
        accuracy_bonus: 1,
        min_damage: 6,
        max_damage: 10,
    },
];

const STAFF_ATTACKS: &[AttackOption] = &[
    AttackOption {
        name: "Arcane Bolt",
        accuracy_bonus: 2,
        min_damage: 5,
        max_damage: 9,
    },
    AttackOption {
        name: "Frost Tap",
        accuracy_bonus: 2,
        min_damage: 4,
        max_damage: 8,
    },
];

const WAND_ATTACKS: &[AttackOption] = &[
    AttackOption {
        name: "Fire Spark",
        accuracy_bonus: 2,
        min_damage: 5,
        max_damage: 10,
    },
    AttackOption {
        name: "Ember Lance",
        accuracy_bonus: 1,
        min_damage: 7,
        max_damage: 11,
    },
];

const WARDEN_BLADE_ATTACKS: &[AttackOption] = &[
    AttackOption {
        name: "Warden Cut",
        accuracy_bonus: 4,
        min_damage: 9,
        max_damage: 14,
    },
    AttackOption {
        name: "Steel Breaker",
        accuracy_bonus: 2,
        min_damage: 12,
        max_damage: 17,
    },
];

const KINGSGUARD_GREATSWORD_ATTACKS: &[AttackOption] = &[
    AttackOption {
        name: "Overhead Cleave",
        accuracy_bonus: 4,
        min_damage: 13,
        max_damage: 19,
    },
    AttackOption {
        name: "Commander's Drive",
        accuracy_bonus: 2,
        min_damage: 16,
        max_damage: 22,
    },
];

const LONGBOW_ATTACKS: &[AttackOption] = &[
    AttackOption {
        name: "Piercing Shot",
        accuracy_bonus: 4,
        min_damage: 8,
        max_damage: 13,
    },
    AttackOption {
        name: "Deadeye Volley",
        accuracy_bonus: 2,
        min_damage: 11,
        max_damage: 16,
    },
];

const DUSKRUNNER_BOW_ATTACKS: &[AttackOption] = &[
    AttackOption {
        name: "Silent Flight",
        accuracy_bonus: 5,
        min_damage: 12,
        max_damage: 18,
    },
    AttackOption {
        name: "Hawkshot",
        accuracy_bonus: 3,
        min_damage: 15,
        max_damage: 21,
    },
];

const STORMGLASS_ROD_ATTACKS: &[AttackOption] = &[
    AttackOption {
        name: "Storm Needle",
        accuracy_bonus: 3,
        min_damage: 9,
        max_damage: 14,
    },
    AttackOption {
        name: "Static Lance",
        accuracy_bonus: 2,
        min_damage: 11,
        max_damage: 17,
    },
];

const ARCHMAGE_FOCUS_ATTACKS: &[AttackOption] = &[
    AttackOption {
        name: "Solar Flare",
        accuracy_bonus: 4,
        min_damage: 12,
        max_damage: 17,
    },
    AttackOption {
        name: "Crown Burst",
        accuracy_bonus: 3,
        min_damage: 15,
        max_damage: 20,
    },
];

const HEALTH_EFFECT: &[ItemEffect] = &[ItemEffect::HealHp(24)];
const GREATER_HEALTH_EFFECT: &[ItemEffect] = &[ItemEffect::HealHp(64)];
const BANDAGE_EFFECT: &[ItemEffect] = &[ItemEffect::HealHp(12)];
const RATION_EFFECT: &[ItemEffect] = &[ItemEffect::HealHp(8), ItemEffect::RestoreStamina(6)];
const MANA_EFFECT: &[ItemEffect] = &[ItemEffect::RestoreMana(18)];
const GREATER_MANA_EFFECT: &[ItemEffect] = &[ItemEffect::RestoreMana(52)];
const STAMINA_EFFECT: &[ItemEffect] = &[ItemEffect::RestoreStamina(18)];
const GREATER_STAMINA_EFFECT: &[ItemEffect] = &[ItemEffect::RestoreStamina(52)];
const ANTIDOTE_EFFECT: &[ItemEffect] = &[ItemEffect::CurePoison];

pub const ITEM_CATALOG: &[ItemDef] = &[
    ItemDef {
        item_type: "health_potion",
        name: "Health Potion",
        description: "A bright red tonic that closes cuts and steadies breathing.",
        kind: ItemKind::Consumable,
        rarity: ItemRarity::Common,
        base_value: 18,
        stackable: true,
        effects: HEALTH_EFFECT,
        equip_slot: None,
        weapon_kind: None,
        attacks: &[],
        equipment_stats: ZERO_EQUIPMENT_STATS,
    },
    ItemDef {
        item_type: "greater_health_potion",
        name: "Greater Health Potion",
        description: "A dense crimson brew reserved for fighters expected to survive brutal wounds.",
        kind: ItemKind::Consumable,
        rarity: ItemRarity::Rare,
        base_value: 95,
        stackable: true,
        effects: GREATER_HEALTH_EFFECT,
        equip_slot: None,
        weapon_kind: None,
        attacks: &[],
        equipment_stats: ZERO_EQUIPMENT_STATS,
    },
    ItemDef {
        item_type: "bandage",
        name: "Bandage",
        description: "Quick field wrap for patching lighter injuries.",
        kind: ItemKind::Consumable,
        rarity: ItemRarity::Common,
        base_value: 8,
        stackable: true,
        effects: BANDAGE_EFFECT,
        equip_slot: None,
        weapon_kind: None,
        attacks: &[],
        equipment_stats: ZERO_EQUIPMENT_STATS,
    },
    ItemDef {
        item_type: "ration",
        name: "Ration",
        description: "Salt meat, hard bread, and enough calories to keep moving.",
        kind: ItemKind::Consumable,
        rarity: ItemRarity::Common,
        base_value: 6,
        stackable: true,
        effects: RATION_EFFECT,
        equip_slot: None,
        weapon_kind: None,
        attacks: &[],
        equipment_stats: ZERO_EQUIPMENT_STATS,
    },
    ItemDef {
        item_type: "mana_tonic",
        name: "Mana Tonic",
        description: "A bitter draught that restores spell reserve.",
        kind: ItemKind::Consumable,
        rarity: ItemRarity::Uncommon,
        base_value: 22,
        stackable: true,
        effects: MANA_EFFECT,
        equip_slot: None,
        weapon_kind: None,
        attacks: &[],
        equipment_stats: ZERO_EQUIPMENT_STATS,
    },
    ItemDef {
        item_type: "greater_mana_tonic",
        name: "Greater Mana Tonic",
        description: "Distilled reserve crystal in liquid form for battle mages with real reserves to restore.",
        kind: ItemKind::Consumable,
        rarity: ItemRarity::Rare,
        base_value: 110,
        stackable: true,
        effects: GREATER_MANA_EFFECT,
        equip_slot: None,
        weapon_kind: None,
        attacks: &[],
        equipment_stats: ZERO_EQUIPMENT_STATS,
    },
    ItemDef {
        item_type: "stamina_draught",
        name: "Stamina Draught",
        description: "Restores drive and clears the ache from tired limbs.",
        kind: ItemKind::Consumable,
        rarity: ItemRarity::Uncommon,
        base_value: 20,
        stackable: true,
        effects: STAMINA_EFFECT,
        equip_slot: None,
        weapon_kind: None,
        attacks: &[],
        equipment_stats: ZERO_EQUIPMENT_STATS,
    },
    ItemDef {
        item_type: "greater_stamina_draught",
        name: "Greater Stamina Draught",
        description: "A veteran marcher’s reserve draught that kicks life back into spent limbs.",
        kind: ItemKind::Consumable,
        rarity: ItemRarity::Rare,
        base_value: 105,
        stackable: true,
        effects: GREATER_STAMINA_EFFECT,
        equip_slot: None,
        weapon_kind: None,
        attacks: &[],
        equipment_stats: ZERO_EQUIPMENT_STATS,
    },
    ItemDef {
        item_type: "antidote",
        name: "Antidote",
        description: "Neutralizes common toxins and clears poison.",
        kind: ItemKind::Consumable,
        rarity: ItemRarity::Common,
        base_value: 14,
        stackable: true,
        effects: ANTIDOTE_EFFECT,
        equip_slot: None,
        weapon_kind: None,
        attacks: &[],
        equipment_stats: ZERO_EQUIPMENT_STATS,
    },
    ItemDef {
        item_type: "iron_sword",
        name: "Iron Sword",
        description: "Reliable steel favored by militia and caravan guards.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Common,
        base_value: 42,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Weapon),
        weapon_kind: Some(WeaponKind::Melee),
        attacks: IRON_SWORD_ATTACKS,
        equipment_stats: EquipmentStats {
            armor: 0,
            attack_bonus: 2,
            spell_power: 0,
            crit_bonus: 0,
            initiative_bonus: 0,
            resistances: ResistanceProfile {
                physical: 0,
                fire: 0,
                frost: 0,
                lightning: 0,
                poison: 0,
                holy: 0,
                shadow: 0,
            },
        },
    },
    ItemDef {
        item_type: "warden_blade",
        name: "Warden Blade",
        description: "A heavy frontier longsword balanced for officers who expect to fight through armored resistance.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Epic,
        base_value: 420,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Weapon),
        weapon_kind: Some(WeaponKind::Melee),
        attacks: WARDEN_BLADE_ATTACKS,
        equipment_stats: EquipmentStats {
            armor: 0,
            attack_bonus: 4,
            spell_power: 0,
            crit_bonus: 2,
            initiative_bonus: 1,
            resistances: ZERO_RESISTANCES,
        },
    },
    ItemDef {
        item_type: "kingsguard_greatsword",
        name: "Kingsguard Greatsword",
        description: "A two-handed wall of steel forged for royal bodyguards expected to break elite lines head-on.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Epic,
        base_value: 760,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Weapon),
        weapon_kind: Some(WeaponKind::Melee),
        attacks: KINGSGUARD_GREATSWORD_ATTACKS,
        equipment_stats: EquipmentStats {
            armor: 0,
            attack_bonus: 6,
            spell_power: 0,
            crit_bonus: 3,
            initiative_bonus: 1,
            resistances: ResistanceProfile {
                physical: 1,
                ..ZERO_RESISTANCES
            },
        },
    },
    ItemDef {
        item_type: "twin_daggers",
        name: "Twin Daggers",
        description: "Light blades built for precise openings and dirty work.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Uncommon,
        base_value: 55,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Weapon),
        weapon_kind: Some(WeaponKind::Melee),
        attacks: TWIN_DAGGER_ATTACKS,
        equipment_stats: EquipmentStats {
            armor: 0,
            attack_bonus: 1,
            spell_power: 0,
            crit_bonus: 3,
            initiative_bonus: 2,
            resistances: ResistanceProfile {
                physical: 0,
                fire: 0,
                frost: 0,
                lightning: 0,
                poison: 0,
                holy: 0,
                shadow: 0,
            },
        },
    },
    ItemDef {
        item_type: "hunting_bow",
        name: "Hunting Bow",
        description: "Yew bow suited to measured pressure at range.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Common,
        base_value: 48,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Weapon),
        weapon_kind: Some(WeaponKind::Ranged),
        attacks: BOW_ATTACKS,
        equipment_stats: EquipmentStats {
            armor: 0,
            attack_bonus: 2,
            spell_power: 0,
            crit_bonus: 1,
            initiative_bonus: 1,
            resistances: ZERO_RESISTANCES,
        },
    },
    ItemDef {
        item_type: "longshot_bow",
        name: "Longshot Bow",
        description: "A masterworked war bow built to punch arrows through mail at distance.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Epic,
        base_value: 430,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Weapon),
        weapon_kind: Some(WeaponKind::Ranged),
        attacks: LONGBOW_ATTACKS,
        equipment_stats: EquipmentStats {
            armor: 0,
            attack_bonus: 4,
            spell_power: 0,
            crit_bonus: 3,
            initiative_bonus: 2,
            resistances: ZERO_RESISTANCES,
        },
    },
    ItemDef {
        item_type: "duskrunner_bow",
        name: "Duskrunner Bow",
        description: "A black-limbed war bow tuned for veteran scouts who kill before the enemy spots the ridge line.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Epic,
        base_value: 720,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Weapon),
        weapon_kind: Some(WeaponKind::Ranged),
        attacks: DUSKRUNNER_BOW_ATTACKS,
        equipment_stats: EquipmentStats {
            armor: 0,
            attack_bonus: 5,
            spell_power: 0,
            crit_bonus: 4,
            initiative_bonus: 3,
            resistances: ZERO_RESISTANCES,
        },
    },
    ItemDef {
        item_type: "apprentice_staff",
        name: "Apprentice Staff",
        description: "A runed staff that steadies novice channeling.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Common,
        base_value: 50,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Weapon),
        weapon_kind: Some(WeaponKind::Magic),
        attacks: STAFF_ATTACKS,
        equipment_stats: EquipmentStats {
            armor: 0,
            attack_bonus: 1,
            spell_power: 3,
            crit_bonus: 0,
            initiative_bonus: 0,
            resistances: ZERO_RESISTANCES,
        },
    },
    ItemDef {
        item_type: "ember_wand",
        name: "Ember Wand",
        description: "A refined focus for aggressive elemental casting.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Rare,
        base_value: 88,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Weapon),
        weapon_kind: Some(WeaponKind::Magic),
        attacks: WAND_ATTACKS,
        equipment_stats: EquipmentStats {
            armor: 0,
            attack_bonus: 1,
            spell_power: 5,
            crit_bonus: 1,
            initiative_bonus: 1,
            resistances: ZERO_RESISTANCES,
        },
    },
    ItemDef {
        item_type: "stormglass_rod",
        name: "Stormglass Rod",
        description: "A prismatic rod that turns disciplined spellwork into battlefield lightning.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Epic,
        base_value: 560,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Weapon),
        weapon_kind: Some(WeaponKind::Magic),
        attacks: STORMGLASS_ROD_ATTACKS,
        equipment_stats: EquipmentStats {
            armor: 0,
            attack_bonus: 2,
            spell_power: 10,
            crit_bonus: 2,
            initiative_bonus: 1,
            resistances: ResistanceProfile {
                lightning: 2,
                ..ZERO_RESISTANCES
            },
        },
    },
    ItemDef {
        item_type: "archmage_focus",
        name: "Archmage Focus",
        description: "A cathedral-cut crystal focus that turns disciplined spellwork into devastating battlefield sorcery.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Epic,
        base_value: 780,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Weapon),
        weapon_kind: Some(WeaponKind::Magic),
        attacks: ARCHMAGE_FOCUS_ATTACKS,
        equipment_stats: EquipmentStats {
            armor: 0,
            attack_bonus: 2,
            spell_power: 13,
            crit_bonus: 3,
            initiative_bonus: 2,
            resistances: ResistanceProfile {
                fire: 2,
                lightning: 2,
                ..ZERO_RESISTANCES
            },
        },
    },
    ItemDef {
        item_type: "wooden_shield",
        name: "Wooden Shield",
        description: "Simple protection that keeps the worst of a blow off your ribs.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Common,
        base_value: 28,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Shield),
        weapon_kind: None,
        attacks: &[],
        equipment_stats: EquipmentStats {
            armor: 3,
            attack_bonus: 0,
            spell_power: 0,
            crit_bonus: 0,
            initiative_bonus: 0,
            resistances: ResistanceProfile {
                physical: 1,
                ..ZERO_RESISTANCES
            },
        },
    },
    ItemDef {
        item_type: "tower_shield",
        name: "Tower Shield",
        description: "An iron-rimmed wall of a shield for those willing to trade grace for survival.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Rare,
        base_value: 340,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Shield),
        weapon_kind: None,
        attacks: &[],
        equipment_stats: EquipmentStats {
            armor: 6,
            attack_bonus: 0,
            spell_power: 0,
            crit_bonus: 0,
            initiative_bonus: 0,
            resistances: ResistanceProfile {
                physical: 4,
                ..ZERO_RESISTANCES
            },
        },
    },
    ItemDef {
        item_type: "bastion_shield",
        name: "Bastion Shield",
        description: "A reinforced line-breaker shield meant for champions who hold the breach while everyone else falls back.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Epic,
        base_value: 620,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Shield),
        weapon_kind: None,
        attacks: &[],
        equipment_stats: EquipmentStats {
            armor: 9,
            attack_bonus: 0,
            spell_power: 0,
            crit_bonus: 0,
            initiative_bonus: 0,
            resistances: ResistanceProfile {
                physical: 6,
                holy: 1,
                ..ZERO_RESISTANCES
            },
        },
    },
    ItemDef {
        item_type: "leather_chest",
        name: "Leather Jerkin",
        description: "Sturdy boiled leather with enough give for active fighting.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Common,
        base_value: 32,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Chest),
        weapon_kind: None,
        attacks: &[],
        equipment_stats: EquipmentStats {
            armor: 4,
            attack_bonus: 0,
            spell_power: 0,
            crit_bonus: 0,
            initiative_bonus: 0,
            resistances: ResistanceProfile {
                physical: 1,
                ..ZERO_RESISTANCES
            },
        },
    },
    ItemDef {
        item_type: "brigandine",
        name: "Brigandine Coat",
        description: "Overlapping steel plates sewn under leather for a traveling officer's protection.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Rare,
        base_value: 520,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Chest),
        weapon_kind: None,
        attacks: &[],
        equipment_stats: EquipmentStats {
            armor: 9,
            attack_bonus: 0,
            spell_power: 0,
            crit_bonus: 0,
            initiative_bonus: 0,
            resistances: ResistanceProfile {
                physical: 3,
                ..ZERO_RESISTANCES
            },
        },
    },
    ItemDef {
        item_type: "leather_legs",
        name: "Leather Greaves",
        description: "Flexible leg guards for long marches and quick turns.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Common,
        base_value: 24,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Legs),
        weapon_kind: None,
        attacks: &[],
        equipment_stats: EquipmentStats {
            armor: 2,
            attack_bonus: 0,
            spell_power: 0,
            crit_bonus: 0,
            initiative_bonus: 1,
            resistances: ZERO_RESISTANCES,
        },
    },
    ItemDef {
        item_type: "ranger_boots",
        name: "Ranger Boots",
        description: "Soft-soled field boots built for speed, stalking, and rapid repositioning.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Rare,
        base_value: 260,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Legs),
        weapon_kind: None,
        attacks: &[],
        equipment_stats: EquipmentStats {
            armor: 3,
            attack_bonus: 0,
            spell_power: 0,
            crit_bonus: 1,
            initiative_bonus: 4,
            resistances: ZERO_RESISTANCES,
        },
    },
    ItemDef {
        item_type: "traveler_cloak",
        name: "Traveler's Cloak",
        description: "Wool and weather-proofing stitched for hard roads.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Common,
        base_value: 20,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Cape),
        weapon_kind: None,
        attacks: &[],
        equipment_stats: EquipmentStats {
            armor: 1,
            attack_bonus: 0,
            spell_power: 0,
            crit_bonus: 0,
            initiative_bonus: 1,
            resistances: ResistanceProfile {
                frost: 1,
                ..ZERO_RESISTANCES
            },
        },
    },
    ItemDef {
        item_type: "phoenix_cloak",
        name: "Phoenix Cloak",
        description: "A firewarded cloak favored by couriers who run through burning siege lines.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Rare,
        base_value: 310,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Cape),
        weapon_kind: None,
        attacks: &[],
        equipment_stats: EquipmentStats {
            armor: 2,
            attack_bonus: 0,
            spell_power: 2,
            crit_bonus: 0,
            initiative_bonus: 2,
            resistances: ResistanceProfile {
                fire: 4,
                frost: 1,
                ..ZERO_RESISTANCES
            },
        },
    },
    ItemDef {
        item_type: "silver_amulet",
        name: "Silver Amulet",
        description: "An old protective charm used to ward restless spirits.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Uncommon,
        base_value: 60,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Neck),
        weapon_kind: None,
        attacks: &[],
        equipment_stats: EquipmentStats {
            armor: 0,
            attack_bonus: 0,
            spell_power: 2,
            crit_bonus: 0,
            initiative_bonus: 0,
            resistances: ResistanceProfile {
                holy: 2,
                shadow: 1,
                ..ZERO_RESISTANCES
            },
        },
    },
    ItemDef {
        item_type: "moonseal_amulet",
        name: "Moonseal Amulet",
        description: "A silvered ward carved with old protective script against cursed and royal dead alike.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Rare,
        base_value: 390,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Neck),
        weapon_kind: None,
        attacks: &[],
        equipment_stats: EquipmentStats {
            armor: 0,
            attack_bonus: 1,
            spell_power: 4,
            crit_bonus: 1,
            initiative_bonus: 0,
            resistances: ResistanceProfile {
                holy: 3,
                shadow: 3,
                poison: 1,
                ..ZERO_RESISTANCES
            },
        },
    },
    ItemDef {
        item_type: "sunfire_talisman",
        name: "Sunfire Talisman",
        description: "A gold-bound charm of mirrored sigils that rewards casters confident enough to stand inside the blast radius.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Epic,
        base_value: 540,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Neck),
        weapon_kind: None,
        attacks: &[],
        equipment_stats: EquipmentStats {
            armor: 0,
            attack_bonus: 1,
            spell_power: 6,
            crit_bonus: 2,
            initiative_bonus: 1,
            resistances: ResistanceProfile {
                fire: 2,
                holy: 4,
                shadow: 2,
                ..ZERO_RESISTANCES
            },
        },
    },
    ItemDef {
        item_type: "scoutmaster_boots",
        name: "Scoutmaster Boots",
        description: "Trail-boots stitched for outriders who survive by moving first and never giving poison a second minute to work.",
        kind: ItemKind::Equipment,
        rarity: ItemRarity::Epic,
        base_value: 460,
        stackable: false,
        effects: &[],
        equip_slot: Some(EquipSlot::Feet),
        weapon_kind: None,
        attacks: &[],
        equipment_stats: EquipmentStats {
            armor: 2,
            attack_bonus: 0,
            spell_power: 0,
            crit_bonus: 2,
            initiative_bonus: 6,
            resistances: ResistanceProfile {
                frost: 1,
                poison: 2,
                ..ZERO_RESISTANCES
            },
        },
    },
    ItemDef {
        item_type: "wolf_pelt",
        name: "Wolf Pelt",
        description: "A thick hide that sells well to fur traders.",
        kind: ItemKind::Loot,
        rarity: ItemRarity::Common,
        base_value: 12,
        stackable: true,
        effects: &[],
        equip_slot: None,
        weapon_kind: None,
        attacks: &[],
        equipment_stats: ZERO_EQUIPMENT_STATS,
    },
    ItemDef {
        item_type: "bandit_seal",
        name: "Blackened Seal",
        description: "A soot-dark seal etched with an ash-mark that does not belong to any common raider band.",
        kind: ItemKind::Loot,
        rarity: ItemRarity::Uncommon,
        base_value: 20,
        stackable: true,
        effects: &[],
        equip_slot: None,
        weapon_kind: None,
        attacks: &[],
        equipment_stats: ZERO_EQUIPMENT_STATS,
    },
    ItemDef {
        item_type: "grave_ash",
        name: "Grave Ash",
        description: "Powder scraped from an active barrow's inner crypt.",
        kind: ItemKind::Loot,
        rarity: ItemRarity::Rare,
        base_value: 26,
        stackable: true,
        effects: &[],
        equip_slot: None,
        weapon_kind: None,
        attacks: &[],
        equipment_stats: ZERO_EQUIPMENT_STATS,
    },
    ItemDef {
        item_type: "old_map",
        name: "Old Map",
        description: "A courier chart detailing paths across the Sunken Road.",
        kind: ItemKind::Quest,
        rarity: ItemRarity::Uncommon,
        base_value: 0,
        stackable: true,
        effects: &[],
        equip_slot: None,
        weapon_kind: None,
        attacks: &[],
        equipment_stats: ZERO_EQUIPMENT_STATS,
    },
    ItemDef {
        item_type: "cipher_scroll",
        name: "Cipher Scroll",
        description: "Sealed orders written in the Mage King's personal cipher, recovered from the Blighted Moor.",
        kind: ItemKind::Quest,
        rarity: ItemRarity::Rare,
        base_value: 0,
        stackable: true,
        effects: &[],
        equip_slot: None,
        weapon_kind: None,
        attacks: &[],
        equipment_stats: ZERO_EQUIPMENT_STATS,
    },
];

pub fn find_def(item_type: &str) -> Option<&'static ItemDef> {
    ITEM_CATALOG.iter().find(|item| item.item_type == item_type)
}

pub fn gear_package_items(gear_name: &str) -> &'static [(&'static str, &'static str)] {
    match gear_name {
        "Melee Kit" => &[
            ("weapon", "iron_sword"),
            ("shield", "wooden_shield"),
            ("chest", "leather_chest"),
            ("legs", "leather_legs"),
        ],
        "Ranged Kit" => &[
            ("weapon", "hunting_bow"),
            ("cape", "traveler_cloak"),
            ("chest", "leather_chest"),
            ("legs", "leather_legs"),
        ],
        "Arcane Kit" => &[
            ("weapon", "apprentice_staff"),
            ("neck", "silver_amulet"),
            ("cape", "traveler_cloak"),
        ],
        "Stealth Kit" => &[
            ("weapon", "twin_daggers"),
            ("cape", "traveler_cloak"),
            ("chest", "leather_chest"),
            ("legs", "leather_legs"),
        ],
        _ => &[],
    }
}
